package it.albemiglio.accounts.core.scan;

import it.albemiglio.accounts.core.modules.Module;
import it.albemiglio.accounts.core.modules.YamlModuleFactory;
import it.albemiglio.accounts.core.modules.replacers.UuidCodec;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.yaml.snakeyaml.Yaml;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DraftWriterTest {

    @Test
    void writesParseableDisabledDraftsGroupedByPluginAndKind(@TempDir Path dir) throws Exception {
        Path db = Paths.get("plugins/PluginB/db.sqlite");
        List<ScanFinding> findings = List.of(
                ScanFinding.file("PluginA", Paths.get("plugins/PluginA/userdata"), "yml", "probe file"),
                ScanFinding.content("PluginA", Paths.get("plugins/PluginA/data.yml"), "probe in content"),
                ScanFinding.sqlite("PluginB", db, "players", "uuid", UuidCodec.DASHED, "probe row"),
                ScanFinding.sqlite("PluginB", db, "players", "raw", UuidCodec.BINARY, "probe row"));
        Path outDir = dir.resolve("drafts");

        Path out = new DraftWriter().write(findings, outDir);

        assertEquals(outDir, out);
        // PluginA has two kinds -> suffixed files; PluginB has one -> plain <plugin>.auto.yml.
        Path fileDraft = outDir.resolve("PluginA-file.auto.yml");
        Path contentDraft = outDir.resolve("PluginA-content.auto.yml");
        Path sqlDraft = outDir.resolve("PluginB.auto.yml");
        for (Path draft : List.of(fileDraft, contentDraft, sqlDraft)) {
            String raw = Files.readString(draft);
            assertTrue(raw.startsWith("# generated by accounts scan"), raw);
            Module module = new YamlModuleFactory().build(new Yaml().load(raw));
            assertFalse(module.isEnabled(), draft.toString());
        }

        Map<String, Object> file = new Yaml().load(Files.readString(fileDraft));
        assertEquals("file", file.get("type"));
        assertEquals(Boolean.FALSE, file.get("enabled"));
        assertEquals("plugins/PluginA/userdata", file.get("directory"));
        assertEquals("yml", file.get("extension"));

        Map<String, Object> content = new Yaml().load(Files.readString(contentDraft));
        assertEquals("content", content.get("type"));
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> targets = (List<Map<String, Object>>) content.get("targets");
        assertEquals(1, targets.size());
        assertEquals("plugins/PluginA/data.yml", targets.get(0).get("directory"));

        Map<String, Object> sql = new Yaml().load(Files.readString(sqlDraft));
        assertEquals("sql", sql.get("type"));
        @SuppressWarnings("unchecked")
        Map<String, Object> database = (Map<String, Object>) sql.get("database");
        assertEquals("sqlite", database.get("type"));
        assertEquals(db.toString(), database.get("database"));
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> replacers = (List<Map<String, Object>>) sql.get("replacers");
        assertEquals(2, replacers.size());
        assertEquals("players", replacers.get(0).get("table"));
        assertEquals("uuid", replacers.get(0).get("column"));
        assertEquals("dashed", replacers.get(0).get("format"));
        assertEquals("binary", replacers.get(1).get("format"));
    }

    @Test
    void unknownBinaryAndUnreadableDatabasesProduceNoDraft(@TempDir Path dir) throws Exception {
        List<ScanFinding> findings = List.of(
                ScanFinding.unknownBinary("PluginX", Paths.get("plugins/PluginX/cache.bin"), "raw bytes"),
                ScanFinding.sqliteError("PluginY", Paths.get("plugins/PluginY/broken.db"), "could not probe"));
        Path outDir = dir.resolve("drafts");

        new DraftWriter().write(findings, outDir);

        assertTrue(Files.isDirectory(outDir));
        try (Stream<Path> drafts = Files.list(outDir)) {
            assertEquals(List.of(), drafts.collect(Collectors.toList()));
        }
    }
}
