package it.albemiglio.accounts.core.scan;

import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Turns {@link Scanner} findings into draft module templates: one {@code <plugin>.auto.yml} per plugin
 * in the output directory (suffixed {@code -file}/{@code -content}/{@code -sql} when one plugin needs
 * several types). Every draft parses through the real {@link it.albemiglio.accounts.core.modules.YamlModuleFactory}
 * but is ALWAYS written with {@code enabled: false} — a scan is a lead, not a verified template, and an
 * auto-generated module must never run without an operator having looked at it. UNKNOWN_BINARY findings
 * (and databases that could not be probed) produce no draft: they are evidence for a human, not a module.
 */
public class DraftWriter {

    private static final String HEADER =
            "# generated by accounts scan — review before enabling; "
            + "verify the column/format against your data\n";

    public Path write(List<ScanFinding> findings, Path outDir) throws IOException {
        Files.createDirectories(outDir);
        Map<String, List<ScanFinding>> byPlugin = new LinkedHashMap<>();
        for (ScanFinding finding : findings) {
            List<ScanFinding> forPlugin = byPlugin.get(finding.getPluginName());
            if (forPlugin == null) {
                forPlugin = new ArrayList<>();
                byPlugin.put(finding.getPluginName(), forPlugin);
            }
            forPlugin.add(finding);
        }
        DumperOptions options = new DumperOptions();
        options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        Yaml yaml = new Yaml(options);
        for (Map.Entry<String, List<ScanFinding>> plugin : byPlugin.entrySet()) {
            writePlugin(yaml, outDir, plugin.getKey(), plugin.getValue());
        }
        return outDir;
    }

    private void writePlugin(Yaml yaml, Path outDir, String plugin, List<ScanFinding> findings)
            throws IOException {
        List<ScanFinding> files = ofKind(findings, ScanFinding.Kind.FILE);
        List<ScanFinding> contents = ofKind(findings, ScanFinding.Kind.CONTENT);
        List<ScanFinding> sqls = new ArrayList<>();
        for (ScanFinding finding : ofKind(findings, ScanFinding.Kind.SQLITE)) {
            // Error findings (database present but unreadable) carry no column: nothing to draft.
            if (finding.getTable() != null) {
                sqls.add(finding);
            }
        }
        boolean suffixed = (files.isEmpty() ? 0 : 1) + (contents.isEmpty() ? 0 : 1)
                + (sqls.isEmpty() ? 0 : 1) > 1;
        if (!files.isEmpty()) {
            String base = suffixed ? plugin + "-file" : plugin;
            Map<String, Object> config = common(base, "file");
            // ponytail: one uuid-keyed store per plugin in practice; extra FILE findings stay report-only.
            config.put("directory", files.get(0).getPath().toString());
            config.put("extension", files.get(0).getExtension());
            writeDraft(yaml, outDir, base, config);
        }
        if (!contents.isEmpty()) {
            String base = suffixed ? plugin + "-content" : plugin;
            Map<String, Object> config = common(base, "content");
            List<Map<String, Object>> targets = new ArrayList<>();
            LinkedHashSet<String> seen = new LinkedHashSet<>();
            for (ScanFinding finding : contents) {
                if (seen.add(finding.getPath().toString())) {
                    targets.add(Collections.singletonMap("directory", finding.getPath().toString()));
                }
            }
            config.put("targets", targets);
            writeDraft(yaml, outDir, base, config);
        }
        if (!sqls.isEmpty()) {
            String base = suffixed ? plugin + "-sql" : plugin;
            Map<String, Object> config = common(base, "sql");
            // ponytail: the draft covers the first database found; findings for any further db files
            // of the same plugin stay report-only (one yml = one module = one database).
            String databaseFile = sqls.get(0).getPath().toString();
            Map<String, Object> database = new LinkedHashMap<>();
            database.put("type", "sqlite");
            database.put("database", databaseFile);
            config.put("database", database);
            List<Map<String, Object>> replacers = new ArrayList<>();
            for (ScanFinding finding : sqls) {
                if (!databaseFile.equals(finding.getPath().toString())) {
                    continue;
                }
                Map<String, Object> replacer = new LinkedHashMap<>();
                replacer.put("table", finding.getTable());
                replacer.put("column", finding.getColumn());
                replacer.put("format", finding.getFormat().name().toLowerCase(Locale.ROOT));
                replacers.add(replacer);
            }
            config.put("replacers", replacers);
            writeDraft(yaml, outDir, base, config);
        }
    }

    private Map<String, Object> common(String name, String type) {
        Map<String, Object> config = new LinkedHashMap<>();
        config.put("name", name.toLowerCase(Locale.ROOT));
        config.put("platform", "SPIGOT");
        config.put("type", type);
        config.put("enabled", false);
        return config;
    }

    private void writeDraft(Yaml yaml, Path outDir, String base, Map<String, Object> config)
            throws IOException {
        String body = HEADER + yaml.dump(config);
        Files.write(outDir.resolve(base + ".auto.yml"), body.getBytes(StandardCharsets.UTF_8));
    }

    private static List<ScanFinding> ofKind(List<ScanFinding> findings, ScanFinding.Kind kind) {
        List<ScanFinding> matches = new ArrayList<>();
        for (ScanFinding finding : findings) {
            if (finding.getKind() == kind) {
                matches.add(finding);
            }
        }
        return matches;
    }
}
